<a href="https://colab.research.google.com/github/nitka975/MachinelLearning/blob/main/%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%BE%D0%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Завантаження датасету (фактичний URL)
url = "movies_metadata.csv"

movies_df = pd.read_csv(url)

# Перегляд перших рядків датасету
movies_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [3]:
# Загальна інформація про датасет
movies_df.info()

# Огляд основних статистичних показників
movies_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8965 entries, 0 to 8964
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  8965 non-null   bool
 1   belongs_to_collection  1273 non-null   object
 2   budget                 8965 non-null   int64
 3   genres                 8965 non-null   object
 4   homepage               565 non-null    object
 5   id                     8965 non-null   int64
 6   imdb_id                8965 non-null   object
 7   original_language      8965 non-null   object
 8   original_title         8965 non-null   object
 9   overview               8940 non-null   object
 10  popularity             8965 non-null   float64
 11  poster_path            8934 non-null   object
 12  production_companies   8965 non-null   object
 13  production_countries   8965 non-null   object
 14  release_date           8960 non-null   object
 15  revenue                8965 non-null   int64
 16  runtime                8959 non-null   float64
 17  spoken_languages       8965 non-null   object
 18  status                 8958 non-null   object
 19  tagline                6378 non-null   object
 20  title                  8964 non-null   object
 21  video                  8964 non-null   object
 22  vote_average           8964 non-null   float64
 23  vote_count             8964 non-null   float64
dtypes: bool(1), float64(4), int64(3), object(16)
memory usage: 1.6+ MB

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,8.965000e+03,8965.000000,8965.000000,8.965000e+03,8959.000000,8964.000000,8964.000000
mean,8.154908e+06,31976.248745,5.054040,2.278666e+07,103.682219,6.109862,191.987394
std,1.986308e+07,42049.026398,4.956321,7.452419e+07,24.534060,1.366752,579.474747
min,0.000000e+00,2.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,0.000000e+00,10141.000000,1.360563,0.000000e+00,91.000000,5.600000,11.000000
50%,0.000000e+00,19513.000000,3.705714,0.000000e+00,101.000000,6.300000,33.000000
75%,5.000000e+06,40220.000000,7.701918,9.114702e+06,113.000000,6.900000,118.250000
max,2.000000e+08,445590.000000,140.950236,1.845034e+09,566.000000,10.000000,9678.000000

In [4]:
# Перевірка наявності пропущених значень
movies_df.isnull().sum()

# Видалення рядків з пропущеними значеннями (якщо їх небагато)
movies_df.dropna(inplace=True)

In [5]:
# Заповнення пропущених значень (якщо значень багато і вони мають важливе значення)
# movies_df['column_name'].fillna(movies_df['column_name'].mean(), inplace=True)

# НОВА ФОРМА ЗАПИСУ
# movies_df.fillna({movies_df['column_name']:"data_value"}, inplace=True)

movies_df["homepage"].fillna("with out link",inplace=True)

/tmp/ipython-input-2787823145.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies_df["homepage"].fillna("with out link",inplace=True)

In [6]:
movies_df.dropna(inplace=True)
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 9 to 8407
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  150 non-null    bool
 1   belongs_to_collection  150 non-null    object
 2   budget                 150 non-null    int64
 3   genres                 150 non-null    object
 4   homepage               150 non-null    object
 5   id                     150 non-null    int64
 6   imdb_id                150 non-null    object
 7   original_language      150 non-null    object
 8   original_title         150 non-null    object
 9   overview               150 non-null    object
 10  popularity             150 non-null    float64
 11  poster_path            150 non-null    object
 12  production_companies   150 non-null    object
 13  production_countries   150 non-null    object
 14  release_date           150 non-null    object
 15  revenue                150 non-null    int64
 16  runtime                150 non-null    float64
 17  spoken_languages       150 non-null    object
 18  status                 150 non-null    object
 19  tagline                150 non-null    object
 20  title                  150 non-null    object
 21  video                  150 non-null    object
 22  vote_average           150 non-null    float64
 23  vote_count             150 non-null    float64
dtypes: bool(1), float64(4), int64(3), object(16)
memory usage: 28.3+ KB

In [7]:
movies_df["release_year"] = pd.to_datetime(movies_df["release_date"]).dt.year

In [8]:
movies_df[["release_date", "release_year"]]

     release_date  release_year
9      1995-11-16          1995
68     1995-04-26          1995
69     1996-01-19          1996
153    1995-09-15          1995
178    1995-06-30          1995
...           ...           ...
8083   2004-08-12          2004
8234   2004-11-05          2004
8257   2004-12-09          2004
8258   2004-12-08          2004
8407   1942-05-27          1942

[150 rows x 2 columns]

Візуалізація даних